eureka:
  client:
    register-with-eureka: false
server:
  port: 8222
spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: employees
          uri: http://localhost:8090
          predicates:
            - Path=/api/v1/employees/**
        - id: departments
          uri: http://localhost:8070
          predicates:
            - Path=/api/v1/departments/**

management:
  tracing:
    sampling:
      probability: 1.0
